### ISSUE TITLE
Suggestion: Do work on branches (for each individual app)

### ISSUE THREAD

**Issue by t3hmrman** [mikeadossi/coding-exercises-js#1]
Hey maybe you should do work on individual branches for all the apps? That way you can open a long-runing PR and I can make comments? Can't see where you're adding stuff/what app you're working on right now

**Comment by t3hmrman** [comment]
I'm also assuming you're working on one app at a time, but it's probably good to get some practice working on branches and merging back into master when you're ready to make the changes more permanent

**Comment by mikeadossi** [comment]
Great idea, I never even considered that. Working solo or not some order makes for good commits.
